### ISSUE TITLE
Issue with beta function

### ISSUE THREAD

**Issue by ernlarson** [cardosopmb/bat#1]
I keep getting the following error in response to trying to run the beta() function. 

Error in if (sum(comm) == 0) return(list(Btotal = 0, Brepl = 0, Brich = 0)) : 
  missing value where TRUE/FALSE needed

There are no NAs in the tree object or the site x species matrix. The issue only arises when I include a tree object in the arguments for beta(). The same species present in the site x species matrix are present in the tree.

Thanks for your help.

**Comment by cardosopmb** [comment]
Hi,

Can you send an example that reproduces the error?

**Comment by ernlarson** [comment]
Issue was an issue with my datafiles, not the package - thanks to Pedro for his help!
